In [1]:
import datetime as dt
import pandas as pd
import pandas_datareader.data as web

pandas_datareader.data library allows you to get API from yahoo finance

In [2]:
start = dt.datetime(2014,10,7)
end = dt.datetime(2019, 10, 7)

With 'start' and 'end' variables you can begin quering the desired stock and it's date range

In [3]:
tsla = web.DataReader('TSLA', 'yahoo', start, end)
abc = web.DataReader('ABC', 'yahoo', start, end)
aapl = web.DataReader('AAPL', 'yahoo', start, end)
amzn = web.DataReader('AMZN', 'yahoo', start, end)
cvs = web.DataReader('CVS', 'yahoo', start, end)
fb = web.DataReader('FB', 'yahoo', start, end)
mck = web.DataReader('MCK', 'yahoo', start, end)
msft = web.DataReader('MSFT', 'yahoo', start, end)
nflx = web.DataReader('NFLX', 'yahoo', start, end)
t = web.DataReader('TS', 'yahoo', start, end)
unh = web.DataReader('UNH', 'yahoo', start, end)
wmt = web.DataReader('WMT', 'yahoo', start, end)
xom = web.DataReader('XOM', 'yahoo', start, end)
ci = web.DataReader('CI', 'yahoo', start, end)
goog = web.DataReader('GOOG', 'yahoo', start, end)
ba = web.DataReader('BA', 'yahoo', start, end)
cnc = web.DataReader('CNC', 'yahoo', start, end)
pfe = web.DataReader('PFE', 'yahoo', start, end)
hum = web.DataReader('HUM', 'yahoo', start, end)
brk_b = web.DataReader('BRK-B', 'yahoo', start, end)

Added stock column with each stock's name to their appropriate dataframe. This is to allow Tableau to display each stock's name once database is imported to Tableau.

In [4]:
aapl['stock']='Apple (AAPL)'
abc['stock']='AmerisourceBergen (ABC)'
amzn['stock']='Amazon (AMZN)'
brk_b['stock']='Berkshire Hathaway (BRK.A)'
cvs['stock']='CVS Health (CVS)'
fb['stock']='Facebook (FB)'
mck['stock']='McKesson (MCK)'
msft['stock']='Microsoft (MSFT)'
nflx['stock']='Netflix (NFLX)'
t['stock']='AT&T (T)'
tsla['stock']='Tesla (TSLA)'
unh['stock']='UnitedHealth (UNH)'
wmt['stock']='Walmart (WMT)'
xom['stock']='Exxon Mobil (XOM)'
ci['stock']='Cigna (CI)'
goog['stock']='Google (GOOG)'
ba['stock']='Boeing (BA)'
cnc['stock']='Centene (CNC)'
pfe['stock']='Pfizer (PFE)'
hum['stock']='Humana (HUM)'

In [5]:
aapl = aapl[['stock'] + aapl.columns[:-1].tolist()]
abc = abc[['stock'] + abc.columns[:-1].tolist()]
amzn = amzn[['stock'] + amzn.columns[:-1].tolist()]
brk_b = brk_b[['stock'] + brk_b.columns[:-1].tolist()]
cvs = cvs[['stock'] + cvs.columns[:-1].tolist()]
fb = fb[['stock'] + fb.columns[:-1].tolist()]
mck = mck[['stock'] + mck.columns[:-1].tolist()]
msft = msft[['stock'] + msft.columns[:-1].tolist()]
nflx = nflx[['stock'] + nflx.columns[:-1].tolist()]
t = t[['stock'] + t.columns[:-1].tolist()]
tsla = tsla[['stock'] + tsla.columns[:-1].tolist()]
unh = unh[['stock'] + unh.columns[:-1].tolist()]
wmt = wmt[['stock'] + wmt.columns[:-1].tolist()]
xom = xom[['stock'] + xom.columns[:-1].tolist()]
ci = ci[['stock'] + ci.columns[:-1].tolist()]
goog = goog[['stock'] + goog.columns[:-1].tolist()]
ba = ba[['stock'] + ba.columns[:-1].tolist()]
cnc = cnc[['stock'] + cnc.columns[:-1].tolist()]
pfe = pfe[['stock'] + pfe.columns[:-1].tolist()]
hum = hum[['stock'] + hum.columns[:-1].tolist()]

In [6]:
amzn.head()

,stock,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,,
2014-10-07,Amazon (AMZN),322.000000,316.670013,319.429993,316.980011,2365400,316.980011
2014-10-08,Amazon (AMZN),324.109985,314.140015,316.579987,322.700012,3452800,322.700012
2014-10-09,Amazon (AMZN),322.269989,314.519989,321.489990,315.369995,3587900,315.369995
2014-10-10,Amazon (AMZN),317.769989,311.380005,314.019989,311.390015,3681900,311.390015
2014-10-13,Amazon (AMZN),313.200012,303.470001,309.869995,306.450012,4363900,306.450012

All stock dataframes combined into list and concat together.

In [7]:
stock_frames=[aapl, abc, amzn, brk_b, cvs, fb, mck, msft, nflx, t, tsla, unh, wmt, xom, ci, goog, ba, cnc, pfe, hum]

In [8]:
combo_frames = pd.concat(stock_frames)

In [9]:
combo_frames.head()

,stock,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,,
2014-10-07,Apple (AAPL),100.120003,98.730003,99.430000,98.750000,42094200.0,90.612694
2014-10-08,Apple (AAPL),101.110001,98.309998,98.760002,100.800003,57404700.0,92.493782
2014-10-09,Apple (AAPL),102.379997,100.610001,101.540001,101.019997,77376500.0,92.695656
2014-10-10,Apple (AAPL),102.029999,100.300003,100.690002,100.730003,66331600.0,92.429558
2014-10-13,Apple (AAPL),101.779999,99.809998,101.330002,99.809998,53583400.0,91.585358

In [10]:
combo_frames.reset_index()

,Date,stock,High,Low,Open,Close,Volume,Adj Close
0,2014-10-07,Apple (AAPL),100.120003,98.730003,99.430000,98.750000,42094200.0,90.612694
1,2014-10-08,Apple (AAPL),101.110001,98.309998,98.760002,100.800003,57404700.0,92.493782
2,2014-10-09,Apple (AAPL),102.379997,100.610001,101.540001,101.019997,77376500.0,92.695656
3,2014-10-10,Apple (AAPL),102.029999,100.300003,100.690002,100.730003,66331600.0,92.429558
4,2014-10-13,Apple (AAPL),101.779999,99.809998,101.330002,99.809998,53583400.0,91.585358
5,2014-10-14,Apple (AAPL),100.519997,98.570000,100.389999,98.750000,63688600.0,90.612694
6,2014-10-15,Apple (AAPL),99.150002,95.180000,97.970001,97.540001,100933600.0,89.502411
7,2014-10-16,Apple (AAPL),97.720001,95.410004,95.550003,96.260002,72154500.0,88.327888
8,2014-10-17,Apple (AAPL),99.000000,96.809998,97.500000,97.669998,68179700.0,89.621696
9,2014-10-20,Apple (AAPL),99.959999,98.220001,98.320000,99.760002,77517300.0,91.539482
10,2014-10-21,Apple (AAPL),103.019997,101.269997,103.019997,102.470001,94623900.0,94.026176
11,2014-10-22,Apple (AAPL),104.110001,102.599998,102.839996,102.989998,68263100.0,94.503311
12,2014-10-23,Apple (AAPL),105.050003,103.629997,104.080002,104.830002,71074700.0,96.191689
13,2014-10-24,Apple (AAPL),105.489998,104.529999,105.180000,105.220001,47053900.0,96.549545
14,2014-10-27,Apple (AAPL),105.480003,104.699997,104.849998,105.110001,34187700.0,96.448616
15,2014-10-28,Apple (AAPL),106.739998,105.349998,105.400002,106.739998,48060900.0,97.944298
16,2014-10-29,Apple (AAPL),107.370003,106.360001,106.650002,107.339996,52687900.0,98.494850
17,2014-10-30,Apple (AAPL),107.349998,105.900002,106.959999,106.980003,40654800.0,98.164513
18,2014-10-31,Apple (AAPL),108.040001,107.209999,108.010002,108.000000,44639300.0,99.100471
19,2014-11-03,Apple (AAPL),110.300003,108.010002,108.220001,109.400002,52282600.0,100.385109
20,2014-11-04,Apple (AAPL),109.489998,107.720001,109.360001,108.599998,41574400.0,99.651047
21,2014-11-05,Apple (AAPL),109.300003,108.129997,109.099998,108.860001,37435900.0,99.889618
22,2014-11-06,Apple (AAPL),108.790001,107.800003,108.599998,108.699997,34968500.0,100.175293
23,2014-11-07,Apple (AAPL),109.320000,108.550003,108.750000,109.010002,33691500.0,100.460983
24,2014-11-10,Apple (AAPL),109.330002,108.669998,109.019997,108.830002,27195500.0,100.295105
25,2014-11-11,Apple (AAPL),109.750000,108.400002,108.699997,109.699997,27442300.0,101.096870
26,2014-11-12,Apple (AAPL),111.430000,109.370003,109.379997,111.250000,46942400.0,102.525322
27,2014-11-13,Apple (AAPL),113.449997,111.599998,111.800003,112.820000,59522900.0,103.972198
28,2014-11-14,Apple (AAPL),114.190002,111.209999,113.150002,114.180000,44063600.0,105.225540
29,2014-11-17,Apple (AAPL),117.279999,113.300003,114.269997,113.989998,46746700.0,105.050430
...,...,...,...,...,...,...,...,...
25170,2019-08-27,Humana (HUM),290.510010,271.940002,289.119995,272.059998,1665200.0,271.493042
25171,2019-08-28,Humana (HUM),279.980011,270.720001,272.059998,276.079987,859400.0,275.504639
25172,2019-08-29,Humana (HUM),280.959991,276.619995,278.880005,279.489990,1093800.0,278.907532
25173,2019-08-30,Humana (HUM),284.709991,279.859985,281.000000,283.209991,633000.0,282.619781
25174,2019-09-03,Humana (HUM),282.839996,277.649994,282.480011,280.359985,716100.0,279.775726
25175,2019-09-04,Humana (HUM),283.989990,272.720001,282.739990,274.179993,1008200.0,273.608612
25176,2019-09-05,Humana (HUM),278.750000,271.390015,277.850006,274.709991,859400.0,274.137512
25177,2019-09-06,Humana (HUM),277.679993,273.040009,274.440002,273.510010,598600.0,272.940033
25178,2019-09-09,Humana (HUM),278.149994,272.269989,273.429993,275.690002,816400.0,275.115479
25179,2019-09-10,Humana (HUM),280.839996,275.709991,276.470001,276.850006,1089100.0,276.273071
25180,2019-09-11,Humana (HUM),278.320007,272.119995,276.200012,276.809998,1066200.0,276.233124
25181,2019-09-12,Humana (HUM),278.920013,267.779999,277.450012,268.380005,1423500.0,267.820709
25182,2019-09-13,Humana (HUM),279.739990,270.399994,270.399994,274.690002,943000.0,274.117554
25183,2019-09-16,Humana (HUM),280.390015,271.950012,271.950012,278.279999,726000.0,277.700073
25184,2019-09-17,Humana (HUM),278.790009,272.350006,278.279999,273.779999,861300.0,273.209442
25185,2019-09-18,Humana (HUM),276.010010,271.660004,273.170013,273.130005,629800.0,272.560822
25186,2019-09-19,Humana (HUM),279.739990,273.239990,273.799988,278.410004,871500.0,277.829803
25187,2019-09-20,Humana (HUM),282.390015,276.760010,279.600006,277.279999,994100.0,276.702148
25188,2019-09-23,Humana (HUM),279.010010,274.079987,275.670013,277.299988,744700.0,276.722107
25189,2019-09-24,Humana (HUM),279.250000,273.559998,277.869995,274.970001,700900.0,274.396973
25190,2019-09-25,Humana (HUM),277.420013,265.179993,274.589996,267.690002,1660600.0,267.132141
25191,2019-09-26,Humana (HUM),268.649994,258.420013,268.100006,263.920013,2324100.0,263.370026
25192,2019-09-27,Humana (HUM),266.970001,256.619995,264.529999,257.589996,1092100.0,257.589996
25193,2019-09-30,Humana (HUM),258.000000,252.089996,253.009995,255.669998,1390300.0,255.669998
25194,2019-10-01,Humana (HUM),256.709991,248.639999,255.949997,254.380005,1319200.0,254.380005
25195,2019-10-02,Humana (HUM),259.089996,252.750000,253.610001,255.490005,1014700.0,255.490005
25196,2019-10-03,Humana (HUM),256.480011,251.479996,255.240005,253.559998,936400.0,253.559998
25197,2019-10-04,Humana (HUM),256.649994,253.009995,253.940002,256.059998,744300.0,256.059998
25198,2019-10-07,Humana (HUM),257.089996,254.449997,255.990005,255.240005,865200.0,255.240005
25199,2019-10-08,Humana (HUM),253.919998,250.520004,252.949997,253.169998,962300.0,253.169998

Combined stock dataframe saved as csv database for Tableau to display visualization.

In [11]:
combo_frames.to_csv('data/project_stocks.csv', index=False)